# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 192.168.1.186
  become: yes

  tasks:

- name: Call Roles
  hosts: 192.168.1.186
  roles:
   #- hostname
   - firewalld
   #- ntp-config
   #- motd
